---

- name: Add Postgres apt repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add Postgres apt repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5"
    update_cache: yes

- name: Install postgresql-client packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - postgresql-client-9.5
